### ISSUE TITLE
build warnings with `MathNet.Numerics`

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#1846]
**Describe the bug**

Many build warnings in CI runs and locally.

[CI output](https://github.com/SMI/SmiServices/actions/runs/9526040511/job/26260951899#step:12:23)

```console
dotnet build --use-current-runtime -p:Platform=x64 --configuration Release --verbosity quiet --nologo
/usr/share/dotnet/sdk/8.0.301/Microsoft.Common.CurrentVersion.targets(2401,5): warning MSB3243:
No way to resolve conflict between "MathNet.Numerics, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cd8b63ad3d691a37"
and "MathNet.Numerics, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null". Choosing "MathNet.Numerics, Version=5.0.0.0,
Culture=neutral, PublicKeyToken=cd8b63ad3d691a37" arbitrarily.
[/home/runner/work/SmiServices/SmiServices/src/common/Smi.Common/Smi.Common.csproj]
```

**Expected behavior**

No build warnings.

**To reproduce**

Checkout and build the repo at commit `018ca35d`

**Additional context**

N/A

**Comment by jas88** [comment]
This is actually an RDMP build issue - https://github.com/HicServices/RDMP/issues/1858 - caused by NPOI referencing a legacy re-pack of the same stats package SynthEHR uses, creating two conflicting references to the same version of `MathNet.Numerics`.

In an ideal world we'd see an updated NPOI release using the mainstream non-legacy version to resolve this. I've tried asking nicely ...
