### ISSUE TITLE
Add Travis build caches

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#56]
For Nuget & Maven packages. See https://docs.travis-ci.com/user/caching/

**Comment by rkm** [comment]
Closed with https://github.com/SMI/SmiServices/commit/848487884a2e2d19fd35ec728d16bf4fe7b4ad42

**Comment by jas88** [comment]
Looks like the .m2 cache is breaking something in Maven - purging cache and restarting a build fixes it, but otherwise we get test failures. I'll look into it in the morning; caching the whole of .m2 is probably too aggressive, and there are a couple of other places we could also use a little caching to good effect.

**Comment by jas88** [comment]
The lack of caching slowed the build down enough to mask a race condition with spinning up Docker containers inside the Travis VM. Switching this to use local packages avoids that robustly, but also exposes a bug in Travis: their Ubuntu 18.04 ("Bionic") build is misconfigured to fetch packages from the 16.04 ("Xenial") servers rather than the correct location. For which there's now a workaround in .travis.yml as well (on the feature/NERasdaemon branch).

(The Maven .m2 cache also now covers the Stanford NER resources, which is a nice side-effect.)
