### ISSUE TITLE
Upgrade to .NET 5

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#707]
Have started testing this on branch https://github.com/SMI/SmiServices/tree/feature/net5, and it seems to "just work".

Are there any other factors to consider, or can we just move forwards with the upgrade?

In terms of developer workflow, I had to update Visual Studio (Windows) and manually install the new SDK (Linux). Other than that I had no issues. Since we package everything self-contained I don't have any worries about having to update anything in the live system.

There seems to be a summary of breaking changes [here](https://docs.microsoft.com/en-us/dotnet/core/compatibility/5.0)
-   I don't spot any obvious issues from that list
-   There seems to be a lot of performance improvements to `System.Text.Json`. We might want to consider if switching to this from `Newtonsoft.Json` will give any performance benefits. Let's measure first though!

**Comment by jas88** [comment]
Since we're going from Core 3.1 to 5.0 almost everything should indeed "just work", and switching the JSON encoder has a lot of potential (particularly in our case: we can cut out the double-conversion via UTF16 before sending UTF8 to Rabbit), though there were a few limitations to check for there.

We've updated other HIC things like RDMP, and essentially it's the older GUI code that breaks when jumping from Framework 4.x: as soon as you get over the hurdle from that to Core 3.1, you're most of the way there.
